# Nome da Aplicação
spring.application.name=controle-ferias-api

# Configurações do PostgreSQL
# Assumindo que você criou um banco chamado 'controle_ferias' no seu Postgres local
spring.datasource.url=jdbc:postgresql://localhost:5432/controle_ferias
spring.datasource.username=postgres
spring.datasource.password=admin

# O Flyway cria as tabelas, então dizemos ao Hibernate apenas para validar (validate)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Mostra as consultas SQL no console (ótimo para debugar)
spring.jpa.show-sql=true